/**
 * scholarships.js
 * 
 * Verified Scholarship Database.
 */

const SCHOLARSHIPS = [
  // --- Merit / Essay / Service ---
  {
    id: 1001,
    name: "Coca-Cola Scholars Program",
    provider: "Coca-Cola Scholars Foundation",
    amount: 20000,
    deadline: "2026-10-31",
    location: "National",
    gpa: 3.0,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "Achievement-based scholarship awarded to graduating high school seniors. Students are recognized for their capacity to lead and serve, as well as their commitment to making a significant impact on their schools and communities.",
    applyLink: "https://www.coca-colascholarsfoundation.org/apply/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 1002,
    name: "Elks Most Valuable Student",
    provider: "Elks National Foundation",
    amount: 50000,
    deadline: "2026-11-15",
    location: "National",
    gpa: 0,
    major: ["All"],
    categories: ["Merit / Essay / Service", "Need-Based"],
    description: "The Elks National Foundation will award 500 four-year scholarships to the highest-rated applicants in the competition. Open to any high school senior who is a citizen of the United States.",
    applyLink: "https://www.elks.org/scholars/scholarships/mvs.cfm",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 1003,
    name: "Cameron Impact Scholarship",
    provider: "Bryan Cameron Education Foundation",
    amount: 0, // Full Tuition
    deadline: "2026-09-08",
    location: "National",
    gpa: 3.7,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "A four-year, full-tuition, impact-based scholarship awarded to exceptional high school students who have demonstrated excellence in leadership, community service, and academics.",
    applyLink: "https://www.bryancameroneducationfoundation.org/scholarship",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 1004,
    name: "Equitable Excellence Scholarship",
    provider: "Equitable Foundation",
    amount: 5000,
    deadline: "2026-12-18",
    location: "National",
    gpa: 0,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "Recognizes students who demonstrate ambition and self-drive to be a force for good in their school, community, or work activities.",
    applyLink: "https://equitable.com/foundation/equitable-excellence-scholarship",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 1006,
    name: "Davidson Fellows Scholarship",
    provider: "Davidson Institute",
    amount: 50000,
    deadline: "2026-02-12",
    location: "National",
    gpa: 0,
    major: ["STEM", "Literature", "Music", "Philosophy"],
    categories: ["Merit / Essay / Service", "STEM", "Arts"],
    description: "The Davidson Fellows Scholarship awards $50,000, $25,000 and $10,000 scholarships to extraordinary young people, 18 and under, who have completed a significant piece of work.",
    applyLink: "https://www.davidsongifted.org/gifted-programs/fellows-scholarship/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 1007,
    name: "Prudential Emerging Visionaries",
    provider: "Prudential Financial",
    amount: 15000,
    deadline: "2026-11-04",
    location: "National",
    gpa: 0,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "Recognizes young people (ages 14-18) for their innovative solutions to financial and societal challenges in their communities.",
    applyLink: "https://www.prudential.com/links/about/emergingvisionaries",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 1008,
    name: "National Space Club Keynote Scholarship",
    provider: "National Space Club",
    amount: 15000,
    deadline: "2026-11-01",
    location: "National",
    gpa: 0,
    major: ["STEM"],
    categories: ["Merit / Essay / Service", "STEM"],
    description: "Awarded to a high school senior, undergraduate or graduate student who intends to pursue a career in the STEM fields and possesses strong public speaking skills.",
    applyLink: "https://www.spaceclub.org/scholarships/index.html",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 1009,
    name: "Voice of Democracy Scholarship",
    provider: "Veterans of Foreign Wars (VFW)",
    amount: 35000,
    deadline: "2026-10-31",
    location: "National",
    gpa: 0,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "The VFW's premier scholarship program. Students in grades 9-12 compete by writing and recording an audio essay on an annual patriotic theme.",
    applyLink: "https://www.vfw.org/community/youth-and-education/youth-scholarships",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 1010,
    name: "GE-Reagan Foundation Scholarship",
    provider: "Ronald Reagan Presidential Foundation",
    amount: 40000,
    deadline: "2026-01-05",
    location: "National",
    gpa: 3.0,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "Honors the legacy of 40th President Ronald Reagan by rewarding college-bound students who demonstrate exemplary leadership, drive, integrity, and citizenship.",
    applyLink: "https://www.reaganfoundation.org/scholarships-education/scholarship-programs/ge-reagan-foundation-scholarship-program/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 1011,
    name: "Jack Kent Cooke College Scholarship",
    provider: "Jack Kent Cooke Foundation",
    amount: 220000,
    deadline: "2025-11-14",
    location: "National",
    gpa: 3.75,
    major: ["All"],
    categories: ["Merit / Essay / Service", "Need-Based"],
    description: "One of the most generous 'last-dollar' scholarships in the U.S., providing up to $55,000 per year for four years to high-achieving seniors with financial need.",
    applyLink: "https://www.jkcf.org/our-scholarships/college-scholarship-program/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 1012,
    name: "James W. McLamore WHOPPER Scholarship",
    provider: "Burger King Foundation",
    amount: 60000,
    deadline: "2025-12-15",
    location: "National",
    gpa: 3.5,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "The top-tier award from the Burger King Scholars program, targeting high-achieving seniors who demonstrate strong leadership and community involvement.",
    applyLink: "https://burgerking.scholarsapply.org/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 1013,
    name: "Ron Brown Scholar Program",
    provider: "Ron Brown Scholar Fund",
    amount: 40000,
    deadline: "2025-12-01",
    location: "National",
    gpa: 3.5,
    major: ["All"],
    categories: ["Merit / Essay / Service", "Identity / Diversity"],
    description: "Awards $10,000 annually to Black/African American seniors who excel academically and exhibit a strong commitment to service. Includes mentoring and a professional network.",
    applyLink: "https://www.ronbrown.org/apply/ron-brown-scholarship/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 1014,
    name: "Amazon Future Engineer Scholarship",
    provider: "Amazon",
    amount: 40000,
    deadline: "2026-01-26",
    location: "National",
    gpa: 2.3,
    major: ["STEM", "Computer Science", "Engineering"],
    categories: ["STEM", "Merit / Essay / Service"],
    description: "Awards $10,000 annually to students planning to study computer science or engineering. Includes a guaranteed paid summer internship at Amazon.",
    applyLink: "https://www.amazonfutureengineer.com/scholarship",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 1015,
    name: "Horatio Alger National Scholarship",
    provider: "Horatio Alger Association",
    amount: 25000,
    deadline: "2026-03-15",
    location: "National",
    gpa: 2.0,
    major: ["All"],
    categories: ["Merit / Essay / Service", "Need-Based"],
    description: "Supports students who have faced and overcome great personal adversity while maintaining a commitment to education and critical financial need.",
    applyLink: "https://scholars.horatioalger.org/scholarships/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 1016,
    name: "Taco Bell Live Más Scholarship",
    provider: "Taco Bell Foundation",
    amount: 25000,
    deadline: "2026-01-06",
    location: "National",
    gpa: 0,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "A non-traditional scholarship focusing on passion over grades. Applicants submit a 2-minute video describing their unique passion and positive impact plan.",
    applyLink: "https://www.tacobellfoundation.org/live-mas-scholarship/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 1017,
    name: "National Honor Society (NHS) Scholarship",
    provider: "NASSP",
    amount: 25000,
    deadline: "2025-11-24",
    location: "National",
    gpa: 3.0,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "Awarded to NHS members who embody the four pillars: Scholarship, Service, Leadership, and Character.",
    applyLink: "https://www.nhs.us/scholarship/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 1018,
    name: "Dr Pepper Tuition Giveaway",
    provider: "Dr Pepper / Keurig Dr Pepper",
    amount: 100000,
    deadline: "2025-09-30",
    location: "National",
    gpa: 0,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "Requires a 60-second video explaining your goals. Finalists compete in a halftime football toss for the grand prize at championship games.",
    applyLink: "https://www.drpepper.com/tuition/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 1019,
    name: "Chick-fil-A Community Scholarship",
    provider: "Chick-fil-A",
    amount: 25000,
    deadline: "2025-10-28",
    location: "National",
    gpa: 3.0,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "Targets community-minded leaders who are not employees. Includes a one-year professional development and mentorship program.",
    applyLink: "https://www.chick-fil-a.com/scholarships",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 1020,
    name: "Dell Scholars Program",
    provider: "Michael & Susan Dell Foundation",
    amount: 20000,
    deadline: "2026-02-15",
    location: "National",
    gpa: 2.4,
    major: ["All"],
    categories: ["Merit / Essay / Service", "Need-Based"],
    description: "Focuses on students who have overcome significant obstacles. Includes a $20,000 scholarship, a new Dell laptop, and textbook credits.",
    applyLink: "https://www.dellscholars.org/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 1021,
    name: "Heisman High School Scholarship",
    provider: "Heisman Trophy Trust",
    amount: 10000,
    deadline: "2025-10-20",
    location: "National",
    gpa: 3.0,
    major: ["All"],
    categories: ["Merit / Essay / Service", "Athletic"],
    description: "Honors high-achieving senior scholar-athletes who are leaders in their schools and communities.",
    applyLink: "https://heismanscholarship.com/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 1022,
    name: "JFK Profile in Courage Essay Contest",
    provider: "John F. Kennedy Presidential Library",
    amount: 10000,
    deadline: "2026-01-12",
    location: "National",
    gpa: 0,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "A prestigious essay contest where students analyze an act of political courage by a U.S. elected official.",
    applyLink: "https://www.jfklibrary.org/learn/education/profile-in-courage-essay-contest",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },

  // --- STEM ---
  {
    id: 2001,
    name: "Lockheed Martin STEM Scholarship",
    provider: "Lockheed Martin",
    amount: 10000,
    deadline: "2026-04-01",
    location: "National",
    gpa: 2.5,
    major: ["Engineering", "Computer Science", "Math", "Physics"],
    categories: ["STEM", "Need-Based"],
    description: "The program is open to individuals who are studying engineering or computer science at a 4-year college or university. Preference is given to students who demonstrate financial need.",
    applyLink: "https://www.lockheedmartin.com/en-us/who-we-are/communities/stem-education/lm-scholarship-program.html",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 2002,
    name: "Microsoft Tuition Scholarship",
    provider: "Microsoft",
    amount: 5000,
    deadline: "2026-01-31",
    location: "National",
    gpa: 3.0,
    major: ["Computer Science", "STEM"],
    categories: ["STEM"],
    description: "Recipients will be awarded in recognition of their demonstrated passion for technology, academic excellence, and leadership while working to push the software industry forward.",
    applyLink: "https://careers.microsoft.com/us/en/scholarships",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 2003,
    name: "SMART Scholarship",
    provider: "Department of Defense",
    amount: 38000,
    deadline: "2026-12-01",
    location: "National",
    gpa: 3.0,
    major: ["STEM"],
    categories: ["STEM", "Merit / Essay / Service"],
    description: "Provides full tuition and a stipend in exchange for employment with the DoD after graduation.",
    applyLink: "https://www.smartscholarship.org/smart",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 2004,
    name: "Generation Google Scholarship",
    provider: "Google",
    amount: 10000,
    deadline: "2026-08-14",
    location: "National",
    gpa: 0,
    major: ["Computer Science", "Computer Engineering", "STEM"],
    categories: ["STEM", "Need-Based", "Identity / Diversity"],
    description: "Supports students pursuing computer science degrees who demonstrate leadership and financial need. Open to current college students and high school seniors in North America.",
    applyLink: "https://buildyourfuture.withgoogle.com/scholarships/generation-google-scholarship",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 2005,
    name: "Adobe Research Women-in-Technology Scholarship",
    provider: "Adobe Research",
    amount: 10000,
    deadline: "2026-03-31",
    location: "National",
    gpa: 0,
    major: ["Computer Science", "Computer Engineering", "STEM"],
    categories: ["STEM", "Identity / Diversity"],
    description: "Recognizes outstanding female undergraduate and master's students in computer science. Award includes a scholarship, mentorship, and a Creative Cloud subscription.",
    applyLink: "https://research.adobe.com/scholarship/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },

  // --- Identity / Diversity ---
  {
    id: 3001,
    name: "The Gates Scholarship",
    provider: "The Bill & Melinda Gates Foundation",
    amount: 0, // Full cost
    deadline: "2025-09-15",
    location: "National",
    gpa: 3.3,
    major: ["All"],
    categories: ["Identity / Diversity", "Need-Based", "Merit / Essay / Service"],
    description: "A highly selective scholarship for outstanding minority high school seniors from low-income households, covering the full cost of attendance not met by other aid.",
    applyLink: "https://www.thegatesscholarship.org/scholarship",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 3002,
    name: "Jackie Robinson Foundation Scholarship",
    provider: "Jackie Robinson Foundation",
    amount: 30000,
    deadline: "2026-01-07",
    location: "National",
    gpa: 3.0,
    major: ["All"],
    categories: ["Identity / Diversity", "Merit / Essay / Service"],
    description: "Provides four-year grants and extensive support services, including mentoring and internship placement, to minority high school seniors.",
    applyLink: "https://jackierobinson.org/apply/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 3003,
    name: "McDonald’s HACER National Scholarship",
    provider: "McDonald's",
    amount: 100000,
    deadline: "2026-02-24",
    location: "National",
    gpa: 2.8,
    major: ["All"],
    categories: ["Identity / Diversity", "Need-Based"],
    description: "One of the largest programs for Hispanic high school seniors in the U.S. Awards are based on academic achievement, financial need, and community involvement.",
    applyLink: "https://www.mcdonalds.com/us/en-us/community/hacer.html",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 3004,
    name: "Women at Microsoft Scholarship",
    provider: "Microsoft",
    amount: 5000,
    deadline: "2026-03-16",
    location: "National",
    gpa: 3.0,
    major: ["STEM", "Technology", "Engineering", "Math", "Computer Science"],
    categories: ["Identity / Diversity", "STEM"],
    description: "Supports high school seniors who identify as women or non-binary pursuing careers in STEAM. Recipients are selected based on their passion for technology and leadership potential.",
    applyLink: "https://www.microsoft.com/en-us/diversity/programs/women-at-microsoft-scholarship",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 3005,
    name: "Oracle Corporate Scholars Program",
    provider: "Oracle / UNCF",
    amount: 10000,
    deadline: "2026-03-11",
    location: "National",
    gpa: 3.0,
    major: ["Business", "Marketing", "HR", "Finance", "Math", "Computer Science", "Computer Engineering"],
    categories: ["Identity / Diversity", "STEM", "Merit / Essay / Service"],
    description: "A partnership between Oracle and UNCF for underrepresented students. Includes a scholarship and a potential paid summer internship at Oracle in technical or business roles.",
    applyLink: "https://opportunities.uncf.org/s/program-landing-page?id=a2i8Y00000AofTwQAJ",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 3006,
    name: "Wells Fargo Scholarship for People with Disabilities",
    provider: "Wells Fargo",
    amount: 2500,
    deadline: "2026-03-20",
    location: "National",
    gpa: 3.0,
    major: ["All"],
    categories: ["Identity / Diversity", "Need-Based"],
    description: "Supports students with disabilities who are high school seniors or current undergraduates. Awards are based on academic record, leadership, and community involvement.",
    applyLink: "https://learnmore.scholarsapply.org/pwdscholarship/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 3007,
    name: "Black at Microsoft (BAM) Scholarship",
    provider: "Microsoft",
    amount: 5000,
    deadline: "2026-03-16",
    location: "National",
    gpa: 3.3,
    major: ["Engineering", "Computer Science", "Business", "Finance", "Marketing"],
    categories: ["Identity / Diversity", "STEM"],
    description: "Awarded to high school seniors of African descent who plan to pursue a career in technology. Provides renewable and one-time awards for students entering college.",
    applyLink: "https://www.microsoft.com/en-us/diversity/programs/black-at-microsoft-scholarship",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 3008,
    name: "HOLA at Microsoft Scholarship",
    provider: "Microsoft",
    amount: 5000,
    deadline: "2026-03-16",
    location: "National",
    gpa: 3.0,
    major: ["Engineering", "Computer Science", "Business", "Marketing"],
    categories: ["Identity / Diversity", "STEM"],
    description: "For high school seniors of Hispanic or Latinx descent pursuing a degree in technology or business. Focuses on leadership and a strong passion for the technology industry.",
    applyLink: "https://www.microsoft.com/en-us/diversity/programs/hola-at-microsoft-scholarship",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 3009,
    name: "Microsoft Disability Scholarship",
    provider: "Microsoft",
    amount: 20000,
    deadline: "2026-03-16",
    location: "National",
    gpa: 2.5,
    major: ["Engineering", "Computer Science", "Business", "Law"],
    categories: ["Identity / Diversity", "STEM"],
    description: "Supports high school seniors with disabilities who are passionate about technology. Provides a renewable award for four years of undergraduate study in the U.S.",
    applyLink: "https://www.microsoft.com/en-us/diversity/programs/microsoft-disability-scholarship",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },

  // --- Regional / State-Specific ---
  {
    id: 5001,
    name: "Florida Bright Futures",
    provider: "Florida Department of Education",
    amount: 0, // Full Tuition
    deadline: "2026-08-31",
    location: "FL",
    gpa: 3.0,
    major: ["All"],
    categories: ["Regional / State-Specific"],
    description: "Lottery-funded scholarships to reward Florida high school graduates for high academic achievement.",
    applyLink: "https://www.floridastudentfinancialaidsg.org/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "High"
  },
  {
    id: 5002,
    name: "Excelsior Scholarship",
    provider: "New York State HESC",
    amount: 5500,
    deadline: "2026-08-31",
    location: "NY",
    gpa: 0,
    major: ["All"],
    categories: ["Regional / State-Specific", "Need-Based"],
    description: "Allows eligible New York State residents to attend a SUNY or CUNY college tuition-free.",
    applyLink: "https://www.hesc.ny.gov/pay-for-college/financial-aid/types-of-financial-aid/nys-grants-scholarships-awards/the-excelsior-scholarship.html",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "High"
  },

  // --- Arts ---
  {
    id: 6001,
    name: "YoungArts Competition",
    provider: "National YoungArts Foundation",
    amount: 10000,
    deadline: "2026-10-15",
    location: "National",
    gpa: 0,
    major: ["Arts"],
    categories: ["Arts", "Merit / Essay / Service"],
    description: "Identifies and supports the most accomplished young artists in the visual, literary and performing arts.",
    applyLink: "https://youngarts.org/apply/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 6002,
    name: "Adobe Design Circle Scholarship",
    provider: "Adobe",
    amount: 25000,
    deadline: "2026-03-12",
    location: "National",
    gpa: 0,
    major: ["Design", "UX/UI", "Product Design", "Industrial Design"],
    categories: ["Arts", "Identity / Diversity"],
    description: "Awarded to students pursuing a degree in a design-related field. Focuses on interaction design, UX/UI, and product design with an emphasis on creating positive social impact.",
    applyLink: "https://www.adobe.com/careers/university/design-circle-scholarship.html",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },

  // --- Athletic ---
  {
    id: 7001,
    name: "Foot Locker Scholar Athletes",
    provider: "Foot Locker",
    amount: 20000,
    deadline: "2026-01-08",
    location: "National",
    gpa: 3.0,
    major: ["All"],
    categories: ["Athletic", "Merit / Essay / Service"],
    description: "Recognizes student-athletes who demonstrate exceptional leadership and sportsmanship in their schools and communities.",
    applyLink: "https://footlockerscholarathletes.com/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  }
];
