/**
 * scholarships.js
 * 
 * Verified Scholarship Database.
 * Schema:
 * {
 *   id: number,
 *   name: string,
 *   provider: string,
 *   amount: number,
 *   deadline: string (ISO Date),
 *   location: string,
 *   gpa: number (min),
 *   major: string[],
 *   categories: string[], // Merit / Essay / Service, STEM, Identity / Diversity, Need-Based, Regional / State-Specific, Arts, Athletic
 *   description: string,
 *   applyLink: string,
 *   verified: boolean,
 *   lastVerified: string (ISO Date),
 *   likelihood: string // 'High', 'Medium', 'Low', 'Unknown'
 * }
 */

const SCHOLARSHIPS = [
  // --- Merit / Essay / Service ---
  {
    id: 1001,
    name: "Coca-Cola Scholars Program Scholarship",
    provider: "Coca-Cola Scholars Foundation",
    amount: 20000,
    deadline: "2026-10-31",
    location: "National",
    gpa: 3.0,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "An achievement-based scholarship awarded to students in their final year of high school. Students are recognized for their capacity to lead and serve, as well as their commitment to making a significant impact on their schools and communities.",
    applyLink: "https://www.coca-colascholarsfoundation.org/apply/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 1002,
    name: "Elks Most Valuable Student Scholarship",
    provider: "Elks National Foundation",
    amount: 50000,
    deadline: "2026-11-15",
    location: "National",
    gpa: 0,
    major: ["All"],
    categories: ["Merit / Essay / Service", "Need-Based"],
    description: "The Elks National Foundation will award 500 four-year scholarships to the highest-rated applicants in the competition. Ranging from $1,000 to $12,500 per year.",
    applyLink: "https://www.elks.org/scholars/scholarships/mvs.cfm",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 1003,
    name: "Cameron Impact Scholarship",
    provider: "Bryan Cameron Education Foundation",
    amount: 0, // Full Tuition
    deadline: "2026-09-08",
    location: "National",
    gpa: 3.7,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "A four-year, full-tuition, impact-based undergraduate scholarship awarded annually to 10-15 exceptional high school students who have demonstrated excellence in leadership, community service, extracurricular activities, and academics.",
    applyLink: "https://www.bryancameroneducationfoundation.org/scholarship",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 1004,
    name: "Equitable Excellence Scholarship",
    provider: "Equitable Foundation",
    amount: 5000,
    deadline: "2026-12-18",
    location: "National",
    gpa: 2.5,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "Recognizes students who demonstrate ambition and self-drive to be a force for good in their school, community, or work activities.",
    applyLink: "https://equitable.com/foundation/equitable-excellence-scholarship",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 1005,
    name: "Burger King Scholars",
    provider: "Burger King McLamore Foundation",
    amount: 1000,
    deadline: "2026-12-15",
    location: "National",
    gpa: 2.5,
    major: ["All"],
    categories: ["Merit / Essay / Service", "Need-Based"],
    description: "Scholarships range from $1,000 to $50,000 and are intended to help students offset the cost of attending college or post-secondary vocational/technical school.",
    applyLink: "https://burgerking.scholarsapply.org/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "High"
  },

  // --- STEM ---
  {
    id: 2001,
    name: "Lockheed Martin STEM Scholarship",
    provider: "Lockheed Martin",
    amount: 10000,
    deadline: "2026-04-01",
    location: "National",
    gpa: 2.5,
    major: ["Engineering", "Computer Science", "Math", "Physics"],
    categories: ["STEM", "Need-Based"],
    description: "The program is open to individuals who are studying engineering or computer science at a 4-year college or university. Preference is given to students who demonstrate financial need.",
    applyLink: "https://www.lockheedmartin.com/en-us/who-we-are/communities/stem-education/lm-scholarship-program.html",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 2002,
    name: "Microsoft Tuition Scholarship",
    provider: "Microsoft",
    amount: 5000,
    deadline: "2026-01-31",
    location: "National",
    gpa: 3.0,
    major: ["Computer Science", "STEM"],
    categories: ["STEM"],
    description: "Recipients will be awarded in recognition of their demonstrated passion for technology, academic excellence, and leadership while working to push the software industry forward.",
    applyLink: "https://careers.microsoft.com/us/en/scholarships",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 2003,
    name: "SMART Scholarship",
    provider: "Department of Defense",
    amount: 38000, // Stipend + Tuition
    deadline: "2026-12-01",
    location: "National",
    gpa: 3.0,
    major: ["STEM"],
    categories: ["STEM", "Merit / Essay / Service"],
    description: "The Science, Mathematics, and Research for Transformation (SMART) Scholarship-for-Service Program provides full tuition and a stipend in exchange for employment with the DoD after graduation.",
    applyLink: "https://www.smartscholarship.org/smart",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 2004,
    name: "Society of Women Engineers Scholarship",
    provider: "SWE",
    amount: 5000,
    deadline: "2026-02-15",
    location: "National",
    gpa: 3.0,
    major: ["Engineering"],
    categories: ["STEM", "Identity / Diversity"],
    description: "SWE Scholarships support those who identify as a woman and pursue an ABET-accredited bachelor or graduate student program in preparation for careers in engineering, engineering technology and computer science.",
    applyLink: "https://swe.org/scholarships/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 2005,
    name: "Generation Google Scholarship",
    provider: "Google",
    amount: 10000,
    deadline: "2026-12-10",
    location: "National",
    gpa: 0,
    major: ["Computer Science"],
    categories: ["STEM", "Identity / Diversity"],
    description: "The Generation Google Scholarship was established to help aspiring students pursuing computer science degrees excel in technology and become leaders in the field.",
    applyLink: "https://buildyourfuture.withgoogle.com/scholarships/generation-google-scholarship",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },

  // --- Identity / Diversity ---
  {
    id: 3001,
    name: "The Gates Scholarship",
    provider: "The Gates Scholarship",
    amount: 0, // Full cost
    deadline: "2026-09-15",
    location: "National",
    gpa: 3.3,
    major: ["All"],
    categories: ["Identity / Diversity", "Need-Based"],
    description: "A highly selective, last-dollar scholarship for outstanding, minority, high school seniors from low-income households.",
    applyLink: "https://www.thegatesscholarship.org/scholarship",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 3002,
    name: "Jackie Robinson Foundation Scholarship",
    provider: "Jackie Robinson Foundation",
    amount: 30000,
    deadline: "2026-01-10",
    location: "National",
    gpa: 0,
    major: ["All"],
    categories: ["Identity / Diversity", "Merit / Essay / Service"],
    description: "Provides four-year scholarships of up to $30,000 and extensive support services, including career guidance and internship placement, to highly motivated African American students.",
    applyLink: "https://jackierobinson.org/apply/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 3003,
    name: "Hispanic Scholarship Fund",
    provider: "HSF",
    amount: 5000,
    deadline: "2026-02-15",
    location: "National",
    gpa: 3.0,
    major: ["All"],
    categories: ["Identity / Diversity", "Need-Based"],
    description: "HSF empowers families with the knowledge and resources to successfully complete a higher education, while providing scholarships and support services to as many exceptional Hispanic American students as possible.",
    applyLink: "https://www.hsf.net/scholarship",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 3004,
    name: "APIAScholars General Scholarship",
    provider: "APIA Scholars",
    amount: 20000,
    deadline: "2026-01-26",
    location: "National",
    gpa: 2.7,
    major: ["All"],
    categories: ["Identity / Diversity", "Need-Based"],
    description: "Scholarships range from one-time $2,500 awards to multi-year $20,000 awards. APIA Scholars provides scholarships to Asian and Pacific Islander Americans with a special focus on those who live at or below the poverty level.",
    applyLink: "https://apiascholars.org/scholarship/apia-scholarship/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 3005,
    name: "Point Foundation Scholarship",
    provider: "Point Foundation",
    amount: 10000,
    deadline: "2026-01-29",
    location: "National",
    gpa: 0,
    major: ["All"],
    categories: ["Identity / Diversity"],
    description: "Point Foundation empowers promising LGBTQ students to achieve their full academic and leadership potential – despite the obstacles often put before them – to make a significant impact on society.",
    applyLink: "https://pointfoundation.org/scholarships",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },

  // --- Need-Based ---
  {
    id: 4001,
    name: "Jack Kent Cooke College Scholarship",
    provider: "Jack Kent Cooke Foundation",
    amount: 55000,
    deadline: "2026-11-18",
    location: "National",
    gpa: 3.5,
    major: ["All"],
    categories: ["Need-Based", "Merit / Essay / Service"],
    description: "The Cooke College Scholarship Program is an undergraduate scholarship program available to high-achieving high school seniors with financial need who seek to attend and graduate from the nation's best four-year colleges and universities.",
    applyLink: "https://www.jkcf.org/our-scholarships/college-scholarship-program/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 4002,
    name: "Horatio Alger Scholarship",
    provider: "Horatio Alger Association",
    amount: 25000,
    deadline: "2026-10-25",
    location: "National",
    gpa: 2.0,
    major: ["All"],
    categories: ["Need-Based"],
    description: "As one of the nation's largest need-based college scholarship programs, the Horatio Alger Scholarship Programs specifically assist high school students who have faced and overcome great obstacles in their young lives.",
    applyLink: "https://scholars.horatioalger.org/about-our-scholarship-programs/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 4003,
    name: "Dell Scholars Program",
    provider: "Michael & Susan Dell Foundation",
    amount: 20000,
    deadline: "2026-12-01",
    location: "National",
    gpa: 2.4,
    major: ["All"],
    categories: ["Need-Based"],
    description: "The Dell Scholars program awards 500 scholarships annually. The program places greater emphasis on a student's determination to succeed than just academic record and test scores.",
    applyLink: "https://www.dellscholars.org/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },

  // --- Regional / State-Specific ---
  {
    id: 5001,
    name: "Florida Bright Futures Scholarship",
    provider: "Florida Department of Education",
    amount: 0, // Full Tuition
    deadline: "2026-08-31",
    location: "State",
    gpa: 3.0,
    major: ["All"],
    categories: ["Regional / State-Specific"],
    description: "Lottery-funded scholarships to reward any Florida high school graduate who merits recognition of high academic achievement.",
    applyLink: "https://www.floridastudentfinancialaidsg.org/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "High"
  },
  {
    id: 5002,
    name: "Excelsior Scholarship",
    provider: "New York State HESC",
    amount: 5500, // Tuition coverage
    deadline: "2026-08-31",
    location: "State",
    gpa: 0,
    major: ["All"],
    categories: ["Regional / State-Specific", "Need-Based"],
    description: "The Excelsior Scholarship, in combination with other student financial aid programs, allows students to attend a SUNY or CUNY college tuition-free.",
    applyLink: "https://www.hesc.ny.gov/pay-for-college/financial-aid/types-of-financial-aid/nys-grants-scholarships-awards/the-excelsior-scholarship.html",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "High"
  },
  {
    id: 5003,
    name: "Georgia HOPE Scholarship",
    provider: "GSFC",
    amount: 0, // Partial/Full Tuition
    deadline: "2026-05-30",
    location: "State",
    gpa: 3.0,
    major: ["All"],
    categories: ["Regional / State-Specific"],
    description: "The HOPE Scholarship provides money to assist eligible students with the educational costs of attending a HOPE Eligible Postsecondary Institution in Georgia.",
    applyLink: "https://www.gafutures.org/hope-state-aid-programs/hope-zell-miller-scholarships/hope-scholarship/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "High"
  },

  // --- Arts ---
  {
    id: 6001,
    name: "YoungArts Competition",
    provider: "National YoungArts Foundation",
    amount: 10000,
    deadline: "2026-10-15",
    location: "National",
    gpa: 0,
    major: ["Arts"],
    categories: ["Arts", "Merit / Essay / Service"],
    description: "YoungArts identifies the most accomplished young artists in the visual, literary and performing arts, and provides them with creative and professional development opportunities.",
    applyLink: "https://youngarts.org/apply/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 6002,
    name: "Scholastic Art & Writing Awards",
    provider: "Alliance for Young Artists & Writers",
    amount: 10000,
    deadline: "2026-12-01",
    location: "National",
    gpa: 0,
    major: ["Arts", "Writing"],
    categories: ["Arts"],
    description: "The nation's longest-running, most prestigious recognition program for creative teens.",
    applyLink: "https://www.artandwriting.org/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 6003,
    name: "Worldstudio AIGA Scholarships",
    provider: "AIGA",
    amount: 6000,
    deadline: "2026-04-15",
    location: "National",
    gpa: 2.0,
    major: ["Design", "Art"],
    categories: ["Arts", "Identity / Diversity"],
    description: "Scholarships are awarded to encourage social and environmental responsibility and cultural awareness in the next generation of artists and designers.",
    applyLink: "https://www.aiga.org/professional-development/scholarships/worldstudio-aiga-scholarships",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },

  // --- Athletic ---
  {
    id: 7001,
    name: "Foot Locker Scholar Athletes",
    provider: "Foot Locker Foundation",
    amount: 20000,
    deadline: "2026-01-08",
    location: "National",
    gpa: 3.0,
    major: ["All"],
    categories: ["Athletic", "Merit / Essay / Service"],
    description: "Honors student-athletes who demonstrate exceptional academic ability and strong leadership skills in sports, in their schools, and within their communities.",
    applyLink: "https://www.footlockerscholarathletes.com/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 7002,
    name: "NCAA Postgraduate Scholarship",
    provider: "NCAA",
    amount: 10000,
    deadline: "2026-05-30",
    location: "National",
    gpa: 3.2,
    major: ["All"],
    categories: ["Athletic"],
    description: "The NCAA awards up to 126 postgraduate scholarships annually. The scholarships are awarded to student-athletes who excel academically and athletically.",
    applyLink: "https://www.ncaa.org/sports/2013/10/21/ncaa-postgraduate-scholarship-program.aspx",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 7003,
    name: "BigSun Scholarship",
    provider: "BigSun Athletics",
    amount: 500,
    deadline: "2026-06-19",
    location: "National",
    gpa: 0,
    major: ["All"],
    categories: ["Athletic"],
    description: "The BigSun Organization is proud to help young athletes succeed in their academic pursuits. All student athletes are eligible for this award, regardless of which sport they are participating in.",
    applyLink: "https://www.bigsunathletics.com/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "High"
  }
];
