/**
 * scholarships.js
 * 
 * Verified Scholarship Database.
 */

const SCHOLARSHIPS = [
  // --- Merit / Essay / Service ---
  {
    id: 1001,
    name: "Coca-Cola Scholars Program",
    provider: "Coca-Cola Scholars Foundation",
    amount: 20000,
    deadline: "2026-10-31",
    location: "National",
    gpa: 3.0,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "Achievement-based scholarship awarded to graduating high school seniors. Students are recognized for their capacity to lead and serve, as well as their commitment to making a significant impact on their schools and communities.",
    applyLink: "https://www.coca-colascholarsfoundation.org/apply/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 1002,
    name: "Elks Most Valuable Student",
    provider: "Elks National Foundation",
    amount: 50000,
    deadline: "2026-11-15",
    location: "National",
    gpa: 0,
    major: ["All"],
    categories: ["Merit / Essay / Service", "Need-Based"],
    description: "The Elks National Foundation will award 500 four-year scholarships to the highest-rated applicants in the competition. Open to any high school senior who is a citizen of the United States.",
    applyLink: "https://www.elks.org/scholars/scholarships/mvs.cfm",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 1003,
    name: "Cameron Impact Scholarship",
    provider: "Bryan Cameron Education Foundation",
    amount: 0, // Full Tuition
    deadline: "2026-09-08",
    location: "National",
    gpa: 3.7,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "A four-year, full-tuition, impact-based scholarship awarded to exceptional high school students who have demonstrated excellence in leadership, community service, and academics.",
    applyLink: "https://www.bryancameroneducationfoundation.org/scholarship",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 1004,
    name: "Equitable Excellence Scholarship",
    provider: "Equitable Foundation",
    amount: 5000,
    deadline: "2026-12-18",
    location: "National",
    gpa: 0,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "Recognizes students who demonstrate ambition and self-drive to be a force for good in their school, community, or work activities.",
    applyLink: "https://equitable.com/foundation/equitable-excellence-scholarship",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 1006,
    name: "Davidson Fellows Scholarship",
    provider: "Davidson Institute",
    amount: 50000,
    deadline: "2026-02-12",
    location: "National",
    gpa: 0,
    major: ["STEM", "Literature", "Music", "Philosophy"],
    categories: ["Merit / Essay / Service", "STEM", "Arts"],
    description: "The Davidson Fellows Scholarship awards $50,000, $25,000 and $10,000 scholarships to extraordinary young people, 18 and under, who have completed a significant piece of work.",
    applyLink: "https://www.davidsongifted.org/gifted-programs/fellows-scholarship/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 1007,
    name: "Prudential Emerging Visionaries",
    provider: "Prudential Financial",
    amount: 15000,
    deadline: "2026-11-04",
    location: "National",
    gpa: 0,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "Recognizes young people (ages 14-18) for their innovative solutions to financial and societal challenges in their communities.",
    applyLink: "https://www.prudential.com/links/about/emergingvisionaries",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 1008,
    name: "National Space Club Keynote Scholarship",
    provider: "National Space Club",
    amount: 15000,
    deadline: "2026-11-01",
    location: "National",
    gpa: 0,
    major: ["STEM"],
    categories: ["Merit / Essay / Service", "STEM"],
    description: "Awarded to a high school senior, undergraduate or graduate student who intends to pursue a career in the STEM fields and possesses strong public speaking skills.",
    applyLink: "https://www.spaceclub.org/scholarships/index.html",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 1009,
    name: "Voice of Democracy Scholarship",
    provider: "Veterans of Foreign Wars (VFW)",
    amount: 35000,
    deadline: "2026-10-31",
    location: "National",
    gpa: 0,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "The VFW's premier scholarship program. Students in grades 9-12 compete by writing and recording an audio essay on an annual patriotic theme.",
    applyLink: "https://www.vfw.org/community/youth-and-education/youth-scholarships",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 1010,
    name: "GE-Reagan Foundation Scholarship",
    provider: "Ronald Reagan Presidential Foundation",
    amount: 40000,
    deadline: "2026-01-05",
    location: "National",
    gpa: 3.0,
    major: ["All"],
    categories: ["Merit / Essay / Service"],
    description: "Honors the legacy of 40th President Ronald Reagan by rewarding college-bound students who demonstrate exemplary leadership, drive, integrity, and citizenship.",
    applyLink: "https://www.reaganfoundation.org/scholarships-education/scholarship-programs/ge-reagan-foundation-scholarship-program/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },

  // --- STEM ---
  {
    id: 2001,
    name: "Lockheed Martin STEM Scholarship",
    provider: "Lockheed Martin",
    amount: 10000,
    deadline: "2026-04-01",
    location: "National",
    gpa: 2.5,
    major: ["Engineering", "Computer Science", "Math", "Physics"],
    categories: ["STEM", "Need-Based"],
    description: "The program is open to individuals who are studying engineering or computer science at a 4-year college or university. Preference is given to students who demonstrate financial need.",
    applyLink: "https://www.lockheedmartin.com/en-us/who-we-are/communities/stem-education/lm-scholarship-program.html",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },
  {
    id: 2002,
    name: "Microsoft Tuition Scholarship",
    provider: "Microsoft",
    amount: 5000,
    deadline: "2026-01-31",
    location: "National",
    gpa: 3.0,
    major: ["Computer Science", "STEM"],
    categories: ["STEM"],
    description: "Recipients will be awarded in recognition of their demonstrated passion for technology, academic excellence, and leadership while working to push the software industry forward.",
    applyLink: "https://careers.microsoft.com/us/en/scholarships",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 2003,
    name: "SMART Scholarship",
    provider: "Department of Defense",
    amount: 38000,
    deadline: "2026-12-01",
    location: "National",
    gpa: 3.0,
    major: ["STEM"],
    categories: ["STEM", "Merit / Essay / Service"],
    description: "Provides full tuition and a stipend in exchange for employment with the DoD after graduation.",
    applyLink: "https://www.smartscholarship.org/smart",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },

  // --- Identity / Diversity ---
  {
    id: 3001,
    name: "The Gates Scholarship",
    provider: "The Gates Scholarship",
    amount: 0, // Full cost
    deadline: "2026-09-15",
    location: "National",
    gpa: 3.3,
    major: ["All"],
    categories: ["Identity / Diversity", "Need-Based"],
    description: "Highly selective, last-dollar scholarship for outstanding, minority, high school seniors from low-income households.",
    applyLink: "https://www.thegatesscholarship.org/scholarship",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },
  {
    id: 3002,
    name: "Jackie Robinson Foundation",
    provider: "Jackie Robinson Foundation",
    amount: 30000,
    deadline: "2026-01-10",
    location: "National",
    gpa: 0,
    major: ["All"],
    categories: ["Identity / Diversity", "Merit / Essay / Service"],
    description: "Provides four-year scholarships and extensive support services to highly motivated African American students.",
    applyLink: "https://jackierobinson.org/apply/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  },

  // --- Regional / State-Specific ---
  {
    id: 5001,
    name: "Florida Bright Futures",
    provider: "Florida Department of Education",
    amount: 0, // Full Tuition
    deadline: "2026-08-31",
    location: "FL",
    gpa: 3.0,
    major: ["All"],
    categories: ["Regional / State-Specific"],
    description: "Lottery-funded scholarships to reward Florida high school graduates for high academic achievement.",
    applyLink: "https://www.floridastudentfinancialaidsg.org/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "High"
  },
  {
    id: 5002,
    name: "Excelsior Scholarship",
    provider: "New York State HESC",
    amount: 5500,
    deadline: "2026-08-31",
    location: "NY",
    gpa: 0,
    major: ["All"],
    categories: ["Regional / State-Specific", "Need-Based"],
    description: "Allows eligible New York State residents to attend a SUNY or CUNY college tuition-free.",
    applyLink: "https://www.hesc.ny.gov/pay-for-college/financial-aid/types-of-financial-aid/nys-grants-scholarships-awards/the-excelsior-scholarship.html",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "High"
  },

  // --- Arts ---
  {
    id: 6001,
    name: "YoungArts Competition",
    provider: "National YoungArts Foundation",
    amount: 10000,
    deadline: "2026-10-15",
    location: "National",
    gpa: 0,
    major: ["Arts"],
    categories: ["Arts", "Merit / Essay / Service"],
    description: "Identifies and supports the most accomplished young artists in the visual, literary and performing arts.",
    applyLink: "https://youngarts.org/apply/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Medium"
  },

  // --- Athletic ---
  {
    id: 7001,
    name: "Foot Locker Scholar Athletes",
    provider: "Foot Locker Foundation",
    amount: 20000,
    deadline: "2026-01-08",
    location: "National",
    gpa: 3.0,
    major: ["All"],
    categories: ["Athletic", "Merit / Essay / Service"],
    description: "Honors student-athletes who demonstrate exceptional academic ability and strong leadership skills in sports and community.",
    applyLink: "https://www.footlockerscholarathletes.com/",
    verified: true,
    lastVerified: "2026-03-13",
    likelihood: "Low"
  }
];
